# This is a basic workflow to help you get started with Actions

name: To test PLSQL Scripts

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - run: mkdir -p /opt/oracle
    - run: cd /opt/oracle
    - run: sudo apt-get update
    - run: sudo apt install alien libaio1
    - run: wget https://download.oracle.com/otn_software/linux/instantclient/2111000/instantclient-sqlplus-linux.x64-21.11.0.0.0dbru.zip
    - run: unzip instantclient-sqlplus-linux.x64-21.11.0.0.0dbru.zip
    - run: ls -la /opt/oracle/
    - run: sudo sh -c "echo /opt/oracle/instantclient_21_8 > /etc/ld.so.conf.d/oracle-instantclient.conf"
    - run: sudo ldconfig
    - run: export LD_LIBRARY_PATH=/opt/oracle/instantclient_21_8:$LD_LIBRARY_PATH
    - run: export PATH=/opt/oracle/instantclient_21_8:$PATH
    - uses: actions/checkout@v3
      # Runs a set of commands using the runners shell
    - name: Get changed files
      id: changed-files-specific
      uses: tj-actions/changed-files@v39
    #  with:
    #    files: |
    #      *.txt
    - name: Run step if any of the listed files above is deleted
      if: steps.changed-files-specific.outputs.added_files == 'true'
      run: |
        for $file in ${{ steps.changed-files-specific.outputs.added_files }}; do
          echo "$file was added"
        done
   
