# This is a basic workflow to help you get started with Actions

name: To test PLSQL Scripts

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a single command using the runners shell
      - name: Install oracle instant client
        run: mkdir -p /opt/oracle
             cd /opt/oracle
             sudo apt install alien libaio1
             wget https://download.oracle.com/otn_software/linux/instantclient/2111000/instantclient-sqlplus-linux.x64-21.11.0.0.0dbru.zip
             unzip instantclient-sqlplus-linux.x64-21.11.0.0.0dbru.zip
      - name: Install Libraries
        run: ls -la /opt/oracle/instantclient_21_8
             sudo sh -c "echo /opt/oracle/instantclient_21_8 > /etc/ld.so.conf.d/oracle-instantclient.conf"
             sudo ldconfig
             export LD_LIBRARY_PATH=/opt/oracle/instantclient_21_8:$LD_LIBRARY_PATH
             export PATH=/opt/oracle/instantclient_21_8:$PATH

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
      - name: Get changed files
        id: changed-files-specific
        uses: tj-actions/changed-files@v38
        with:
          files: |
            *.txt

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v39

      - name: List all added files
        run: |
          for file in ${{ steps.changed-files.outputs.added_files }}; do
            echo "$file was added"
          done
